version: '3.5'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taco_cloud
    ports:
      - "5432:5432"
    restart: unless-stopped